version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PSWD} #optional
      - SUDO_PASSWORD=${SU_PSWD} #optional
      - PROXY_DOMAIN=code.${DOMAIN} #optional
      - DEFAULT_WORKSPACE=/root #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.entrypoints=https"
      - "traefik.http.routers.code.rule=Host(`code.${DOMAIN}`)"
      - "traefik.http.services.code.loadbalancer.server.port=8443"
    networks:
      - proxy
    volumes:
      - /root:/root
    restart: unless-stopped
networks:
  proxy:
    external: true