---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

# List of users
users:
  admin:
    displayname: "Admin Name"
    # Password is Authelia
    password:
    email: rutvik2611@gmail.com
    groups:
      - admins
      - dev
...