version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL="${CF_API_EMAIL}"
      - CF_DNS_API_TOKEN="${CF_DNS_API_TOKEN}"
      - CF_API_KEY="${CF_DNS_API_TOKEN}"
      - DOCKER_HOST=/var/run/docker.sock
      # be sure to use the correct one depending on if you are using a token or key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    labels:
      traefik.http.routers.api.rule: Host(`tr.${DOMAIN}`)    # Define the subdomain for the traefik dashboard.
      traefik.http.routers.api.entryPoints: https    # Set the Traefik entry point.
      traefik.http.routers.api.service: api@internal    # Enable Traefik API.
      traefik.enable: true   # Enable Traefik reverse proxy for the Traefik dashboard.

networks:
  proxy:
    external: true