version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=rutvik2611@gmail.com
      - CF_DNS_API_TOKEN=HAHA-----Nope--Change--This
      - CF_API_KEY=HAHA-----Nope--Change--This
      # be sure to use the correct one depending on if you are using a token or key
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/rpserver/traefik/data/traefik.yml:/traefik.yml:ro
      - /home/rpserver/traefik/data/acme.json:/acme.json
      - /home/rpserver/traefik/data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`tr.rutvik2611.com`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=lol:loooooooop"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`tr.rutvik2611.com`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main=rutvik2611.com"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.rutvik2611.com"
      - "traefik.http.routers.traefik-secure.service=api@internal"

networks:
  proxy:
    external: true

