version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID={rPUID}
      - PGID={rGUID}
      - TZ={TZ}
      - WEBUI_PORT=8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config:rw
      - ./theme/vuetorrent:/data
      - ${SHAREDFOLDER:?err}:/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.qbit.entryPoints: https
      traefik.http.routers.qbit.rule: Host(`qbit.${DOMAIN:?err}`)
      traefik.http.services.qbit.loadbalancer.server.port: 8080
    restart: unless-stopped
    networks:
      - proxy
networks:
  proxy:
    external:
      name: proxy